### ISSUE TITLE
This theme is broken?

### ISSUE THREAD

**Issue by braco** [NodeBB/nodebb-theme-quickstart#11]
```
$ cd /project

$ git clone https://github.com/NodeBB/nodebb-theme-quickstart.git
  Cloning into 'nodebb-theme-quickstart'...
  ..

$ npm install ./nodebb-theme-quickstart/
  ...

$ ./nodebb reset -t quickstart
  error: [themes] Unable to resolve this theme's templates. Expected to be at "templates/" or defined in the "templates" property of "theme.json"

$ mkdir nodebb-theme-quickstart/templates

$ ./nodebb reset -t quickstart && ./nodebb build
```

Navigate to `https://local.dev/login`

Error code 500

I'm not sure where to see more detailed error messages, but I'm noticing relative paths like `@import "../nodebb-theme-harmony/theme";`, which might be breaking with that local folder style of `npm install` above?

(I'm cloning into a local folder and installing from there to emulate what installing a custom theme might look like without npm link, but `npm install http://..` produces the same 500 error)

Are there any working child themes floating around?

**Comment by barisusakli** [comment]
@braco thanks for reporting, please let me know if it works with above changes. The missing templates folder was probably the issue. Even if you don't have any templates that folder is still required.

**Comment by braco** [comment]
That works @barisusakli, thank you!
