### ISSUE TITLE
CSS not loading from parent theme

### ISSUE THREAD

**Issue by saikarthikp9** [NodeBB/nodebb-theme-quickstart#9]
I have followed the steps here and updated just the category.tpl file:  
[Fork](https://github.com/saikarthikp9/nodebb-theme-harmony-op)
[NPM](https://www.npmjs.com/package/nodebb-theme-harmony-op)

But when installed, the styling does not load on the forum page. Similar to screenshot below. Any ideas?

<img width="296" alt="Screenshot 2023-10-06 at 4 37 56 PM" src="https://github.com/NodeBB/nodebb-theme-quickstart/assets/69390532/d8be3cc6-0708-4bd1-b142-c0e216a232c2">

**Comment by barisusakli** [comment]
@saikarthikp9 copy the contents of overrides.scss from harmony theme to your fork, without that the build will error and you won't get any css. You can then modify the values in overrides.scss if you want to change colors or modify bootstrap features.

**Comment by saikarthikp9** [comment]
@barisusakli, awesome that worked! 

But, now [my category template file](https://github.com/saikarthikp9/nodebb-theme-harmony-op/blob/433e17fec1bafb69a714c95b553826e6e5ae77e1/templates/category.tpl#L5) is not getting used. Do you see anything wrong?
